"""
export_xattn_mesh.py
--------------------
Export a GLB (and PLY) for a CROSS-ATTENTION rung: rung15 / rung16 / rung17.

WHY export_frame_mesh.py cannot do this
  That script reads runs/<run>/slat_cache.npz. rung13 has one because its
  adapter lives in the DECODER, so the SLaT is identical every epoch and can be
  cached once. The cross-attention rungs edit the flow itself, so the SLaT
  depends on the adapter and there is nothing to cache -- those run dirs have no
  slat_cache.npz at all. The latent has to be regenerated by running the ODE.

WHAT THIS DOES
  frame -> DINOv2 -> 25-step Euler ODE with the LoRA active -> SLaT
        -> frozen slat_decoder_mesh -> mesh -> rung13 alignment -> GLB + PLY

  Writes BOTH arms for the same frame so they are directly comparable:
      frozen_f####.glb    stock TRELLIS, LoRA off
      result_f####.glb    the adapted run

  Vertex colours are per-vertex (TRELLIS has no UVs), carried into the GLB via
  trimesh's vertex_colors, which is what glb_to_ply.py already documents as the
  exact, non-resampled path.

ALIGNMENT
  rung13's solved mesh->video similarity is applied to the vertices before
  export, matching every render in this project. --no-align writes the raw mesh.

Usage:
  python render/export_xattn_mesh.py --run rung15v1_... --frame 1
"""

import sys, os, argparse, json, math, gc
from pathlib import Path

os.environ['SPCONV_ALGO']           = 'native'
os.environ.setdefault('ATTN_BACKEND', 'xformers')
os.environ['HF_HOME']              = '/net/scratch/rajhansini/.cache/huggingface'
os.environ['HF_HUB_OFFLINE']       = '1'
os.environ['TRANSFORMERS_OFFLINE'] = '1'
os.environ.setdefault('PYTORCH_CUDA_ALLOC_CONF', 'expandable_segments:True')

_HERE = Path(__file__).resolve().parent
_ROOT = _HERE.parent
_LEX  = _ROOT / 'experiments' / 'lora_experiments'
_VIS  = _LEX / 'visibility'
_PIPE = _ROOT / 'experiments' / 'dynamic_texture_trellis_pipeline'

ap = argparse.ArgumentParser()
ap.add_argument('--run',   default='rung15v1_uniform_all_qkvo_r4_s6_2674ec70')
ap.add_argument('--ckpt',  default='lora_best.pt')
ap.add_argument('--frame', type=int, default=1)
ap.add_argument('--out-dir', default=None)
ap.add_argument('--no-align', action='store_true')
ap.add_argument('--no-glb', action='store_true')
args = ap.parse_args()

OUT = Path(args.out_dir) if args.out_dir else (_HERE / 'out' / f'{args.run[:8]}_f{args.frame:04d}')
OUT.mkdir(parents=True, exist_ok=True)


def _ensure_nvdiffrast():
    import subprocess as _sp, torch
    p = torch.cuda.get_device_properties(0)
    tag, arch = f'sm{p.major}{p.minor}', f'{p.major}.{p.minor}'
    local = f'/tmp/nvdiffrast_{tag}'
    if os.path.isdir(local) and local not in sys.path:
        sys.path.insert(0, local)
    try:
        import nvdiffrast.torch as dr
        g = dr.RasterizeCudaContext(); del g
        print('[NVDIFF] OK', flush=True); return
    except Exception as e:
        print(f'[NVDIFF] {e}', flush=True)
    if os.environ.get('_NVDIFF_REBUILT') == tag:
        raise RuntimeError(f'nvdiffrast broken for {tag}')
    src = f'/tmp/nvdiff_src_{tag}_{os.getpid()}'
    os.makedirs(src, exist_ok=True)
    pip = '/net/projects/ranalab/rajhansini/conda_envs/trellis/bin/pip'
    env = {**os.environ, 'TORCH_CUDA_ARCH_LIST': arch}
    _sp.run(['git', 'clone', 'https://github.com/NVlabs/nvdiffrast.git',
             f'{src}/nvdiffrast', '--depth', '1', '--quiet'], check=True, env=env)
    _sp.run([pip, 'install', '.', '--target', local, '--no-build-isolation',
             '--no-cache-dir', '--no-deps', '-q'], cwd=f'{src}/nvdiffrast', env=env, check=True)
    os.environ['_NVDIFF_REBUILT'] = tag
    os.execv(sys.executable, [sys.executable] + sys.argv)


_ensure_nvdiffrast()

import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
import torchvision.transforms as T
import trimesh
from PIL import Image
from contextlib import contextmanager

sys.path.insert(0, str(_ROOT)); sys.path.insert(0, str(_PIPE))
from trellis.pipelines import TrellisImageTo3DPipeline
from trellis.modules import sparse as sp
from trellis.modules.sparse.attention import sparse_scaled_dot_product_attention
from step8_decode_render.decode_render import normalize_slat

DEVICE = torch.device('cuda')
GT_FRAMES_DIR = Path('/net/projects/ranalab/rajhansini/MV-Adapter-Experimental'
                     '/outputs/teapot_lava_kling_premium'
                     '/teapot_lava_kling_premium_front/all_frames_150')
PRETRAINED, STRUCT_SEED, NOISE_SEED = 'JeffreyXiang/TRELLIS-image-large', 42, 6
STEPS, RESCALE_T = 25, 3.0
_ts = np.linspace(1, 0, STEPS + 1); _ts = RESCALE_T * _ts / (1 + (RESCALE_T - 1) * _ts)
T_PAIRS = [(_ts[i], _ts[i + 1]) for i in range(STEPS)]
_DINO_NORM = T.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
ALIGN = json.load(open(_VIS / 'alignment' / 'alignment.json'))


def rodrigues(rv):
    th = float(np.linalg.norm(rv)) + 1e-12
    k = np.asarray(rv, dtype=np.float64) / th
    K = np.array([[0, -k[2], k[1]], [k[2], 0, -k[0]], [-k[1], k[0], 0]])
    return np.eye(3) + math.sin(th) * K + (1 - math.cos(th)) * (K @ K)


_AS = float(ALIGN['scale'])
_AR = torch.tensor(rodrigues(ALIGN['rotvec']), dtype=torch.float32, device=DEVICE)
_AC = torch.tensor(ALIGN['centre'], dtype=torch.float32, device=DEVICE)
_AT = torch.tensor(ALIGN['translation'], dtype=torch.float32, device=DEVICE)


def align(v): return _AS * ((v - _AC) @ _AR.T) + _AC + _AT


def encode(dino, i):
    img = Image.open(GT_FRAMES_DIR / f'frame_{i:04d}.png').convert('RGB') \
               .resize((518, 518), Image.LANCZOS)
    a = np.array(img).astype(np.float32) / 255.0
    x = _DINO_NORM(torch.from_numpy(a).permute(2, 0, 1)).unsqueeze(0).to(DEVICE)
    with torch.no_grad():
        f = dino(x, is_training=True)['x_prenorm']
        return F.layer_norm(f, f.shape[-1:]).squeeze(0)


class LoRALayer(nn.Module):
    def __init__(self, i, o, r):
        super().__init__()
        self.A = nn.Parameter(torch.zeros(r, i)); self.B = nn.Parameter(torch.zeros(o, r))
    def forward(self, x): return ((x.float() @ self.A.T) @ self.B.T).to(x.dtype)


class XAttnLoRABundle(nn.Module):
    def __init__(self, ca, rank, targets):
        super().__init__()
        self.targets = tuple(targets)
        for n in self.targets:
            lin = getattr(ca, n)
            setattr(self, f'lora_{n}', LoRALayer(lin.in_features, lin.out_features, rank))
    def get(self, n):
        return getattr(self, f'lora_{n}', None) if n in self.targets else None


class XAttnLoRARegistry(nn.Module):
    def __init__(self, fm, active, rank, targets):
        super().__init__()
        mods, i = {}, 0
        for blk in fm.blocks:
            if not hasattr(blk, 'cross_attn'): continue
            if i in set(active): mods[str(i)] = XAttnLoRABundle(blk.cross_attn, rank, targets)
            i += 1
        self.blocks = nn.ModuleDict(mods)
    def get(self, i):
        k = str(i); return self.blocks[k] if k in self.blocks else None


LORA = None


def _fwd(module, x, context, idx):
    """modules.py:126-139 plus the three LoRA deltas. Nothing else changed."""
    lb = LORA.get(idx) if LORA is not None else None
    q_sp = module._linear(module.to_q, x)
    if lb is not None and lb.get('to_q') is not None:
        q_sp = q_sp.replace(q_sp.feats + lb.get('to_q')(x.feats).to(q_sp.feats.dtype))
    q = module._reshape_chs(q_sp, (module.num_heads, -1))
    kv_t = module._linear(module.to_kv, context)
    if lb is not None and lb.get('to_kv') is not None:
        kv_t = kv_t + lb.get('to_kv')(context).to(kv_t.dtype)
    kv = module._fused_pre(kv_t, num_fused=2)
    h = sparse_scaled_dot_product_attention(q, kv)
    h = module._reshape_chs(h, (-1,))
    out = module._linear(module.to_out, h)
    if lb is not None and lb.get('to_out') is not None:
        out = out.replace(out.feats + lb.get('to_out')(h.feats).to(out.feats.dtype))
    return out


@contextmanager
def lora_ctx(fm):
    saved, i = {}, 0
    for blk in fm.blocks:
        if not hasattr(blk, 'cross_attn'): continue
        ca = blk.cross_attn; saved[i] = ca.forward
        def _mk(m, idx):
            def _f(x, context=None): return _fwd(m, x, context, idx)
            return _f
        ca.forward = _mk(ca, i); i += 1
    assert i == 24, f'expected 24 cross-attn blocks, found {i}'
    try: yield
    finally:
        j = 0
        for blk in fm.blocks:
            if hasattr(blk, 'cross_attn') and j in saved:
                blk.cross_attn.forward = saved[j]; j += 1


def denoise(fm, noise, coords, cond):
    x = sp.SparseTensor(feats=noise.clone(), coords=coords)
    with torch.no_grad(), lora_ctx(fm):
        for t, tp in T_PAIRS:
            tt = torch.tensor([1000.0 * t], device=DEVICE, dtype=torch.float32)
            v = fm(x, tt, cond)
            x = x.replace(x.feats - (t - tp) * v.feats)
    return normalize_slat(x)


def write(mesh, tag):
    v = mesh.vertices.detach()
    f = mesh.faces.detach()
    # drop degenerate faces, exactly as every render in this project does
    e1, e2 = v[f[:, 1]] - v[f[:, 0]], v[f[:, 2]] - v[f[:, 0]]
    f = f[0.5 * torch.cross(e1, e2, dim=1).norm(dim=1) > 1e-6]
    if not args.no_align:
        v = align(v)
    col = mesh.vertex_attrs[:, :3].detach().clamp(0, 1)
    vc = (col.cpu().numpy() * 255).astype(np.uint8)
    vc = np.concatenate([vc, np.full((len(vc), 1), 255, np.uint8)], axis=1)
    tm = trimesh.Trimesh(vertices=v.cpu().numpy().astype(np.float64),
                         faces=f.cpu().numpy(), vertex_colors=vc, process=False)
    outs = []
    p = OUT / f'{tag}_f{args.frame:04d}.ply'; tm.export(str(p)); outs.append(p)
    if not args.no_glb:
        g = OUT / f'{tag}_f{args.frame:04d}.glb'; tm.export(str(g)); outs.append(g)
    b = tm.bounds
    print(f'  {tag:8s} {len(tm.vertices):>8,} verts  {len(tm.faces):>8,} faces  '
          f'mean RGB {vc[:, :3].mean(0).round(1).tolist()}')
    print(f'           bounds {np.round(b[0],3).tolist()} .. {np.round(b[1],3).tolist()}')
    for o in outs:
        print(f'           wrote {o.name}  ({o.stat().st_size/1e6:.1f} MB)', flush=True)


def main():
    print('=' * 84)
    print(f'EXPORT  run={args.run}  frame={args.frame}  aligned={not args.no_align}')
    print('=' * 84, flush=True)

    pipe = TrellisImageTo3DPipeline.from_pretrained(PRETRAINED); pipe.to(DEVICE)
    fm, dec = pipe.models['slat_flow_model'], pipe.models['slat_decoder_mesh']
    for p in fm.parameters(): p.requires_grad_(False)
    for p in dec.parameters(): p.requires_grad_(False)

    ref = Image.open(GT_FRAMES_DIR / 'frame_0075.png').convert('RGB')
    cs = pipe.get_cond([ref]); torch.manual_seed(STRUCT_SEED)
    coords = pipe.sample_sparse_structure(cs, num_samples=1)
    assert coords.shape[0] == 7301, f'N_vox={coords.shape[0]} != 7301'
    del cs; gc.collect(); torch.cuda.empty_cache()
    for n in list(pipe.models):
        if n not in {'slat_flow_model', 'slat_decoder_mesh', 'image_cond_model'}:
            try: pipe.models[n].cpu()
            except Exception: pass

    dino = pipe.models['image_cond_model'].to(DEVICE)
    cond = encode(dino, args.frame).unsqueeze(0).to(DEVICE)
    dino.cpu(); gc.collect(); torch.cuda.empty_cache()
    torch.manual_seed(NOISE_SEED)
    noise = torch.randn(coords.shape[0], fm.in_channels, device=DEVICE)

    rd = _LEX / 'runs' / args.run
    cfg = json.load(open(rd / 'config.json'))
    ck = torch.load(rd / 'lora_ckpts' / args.ckpt, map_location='cpu', weights_only=True)
    reg = XAttnLoRARegistry(fm, cfg['active_blocks'], cfg['rank'],
                            tuple(cfg['targets'])).to(DEVICE)
    reg.load_state_dict(ck['registry_state'], strict=True); reg.eval()
    bmax = max(float(getattr(b, f'lora_{n}').B.float().norm())
               for b in reg.blocks.values() for n in b.targets)
    assert bmax > 1e-6, 'LoRA B all zero -- adapter not loaded'
    print(f'[LORA] epoch {ck["epoch"]}  psnr {ck["best_psnr"]:.3f}  '
          f'blocks {len(cfg["active_blocks"])}  targets {tuple(cfg["targets"])}  '
          f'max||B|| {bmax:.4f}\n', flush=True)

    global LORA
    for tag, L in (('frozen', None), ('result', reg)):
        LORA = L
        slat = denoise(fm, noise, coords, cond)
        with torch.no_grad():
            mesh = dec(slat)[0]
        write(mesh, tag)
        del slat, mesh
        gc.collect(); torch.cuda.empty_cache()

    print(f'\n[DONE] {OUT}')
    print('=' * 84, flush=True)


if __name__ == '__main__':
    main()
